### ISSUE TITLE
Add "bundle" task that for webpack

### ISSUE THREAD

**Issue by bitspook** [gajus/pragmatist#12]
Do you think it makes sense to have a `pragmatist bundle` task which would use webpack to bundle all the resources? I am unsure if we should have it in pragmatist, but it makes a lot of sense to have something similar. Most of our projects have more or less same webpack config. build/lint/test tasks make life so much easier.

If you think it does make sense, next step would of course be a `serve` task :stuck_out_tongue: , which would setup a browser-sync + react-transform + webpack-hot-reload server for development. We will essentially have no setup-boilerplate to create/maintain if pragmatist can do this.

**Comment by gajus** [comment]
What about having a custom babel preset for webpack? Then you'd need only one build specific babel dependency.

**Comment by bitspook** [comment]
Dependencies is not the problem, the config that needs to be copied over every time is. Pragmatist does its job well for creating react components, but for end-user apps (like component examples, and other user facing apps), we have webpack config, and browsersync setup (when we want it). These need to be copied/duplicated-with-effort over every time. When we have to make some changes, they need to be made in all of them (some of them often gets missed).

Do you think it's a good idea to have webpack/browsersync setup somehow unified?

**Comment by gajus** [comment]
I don't see how a "bundle" talk could be standardised. There are too many variables in the webpack setup, e.g.
- The plugins vary greatly depending on the requirements (React, CSS Modules, SCSS, PostCSS, etc.)
- There is plugin specific configuration (e.g. `webpack.ProvidePlugin`, `webpack.optimize.CommonsChunkPlugin`) configuration.
- There is alias configuration.
- There is loader configuration.

The list goes on.

I think for the use case you are describing it would be best to have a repository holding common setup examples and just rely on the copy paste.

We are not maintaining that many project for this to be a problem.

**Comment by gajus** [comment]
If we were to do such a tool though, it would be outside of pragmatist. I am positioning this tool as more or less suitable for any npm package build process. `webpack` is hardly a common NPM dependency.
