### ISSUE TITLE
Compiling scss to scss

### ISSUE THREAD

**Issue by liady** [gajus/pragmatist#16]
Is it possible to also compile scss to css files in the build task?

**Comment by gajus** [comment]
How would you do that?

This would either assume that files need to be compiled in the same folder (not a good idea) or would require some sort of configuration.

Besides, package bundlers (such as webpack) handle converting SCSS to CSS.

Finally, you can simply extend Pragmatist tasks. See https://github.com/gajus/pragmatist#gulp-tasks

**Comment by liady** [comment]
Valid points, thanks.
I will add my own build step to compile scss.
Great package!
