### ISSUE TITLE
Create local config files

### ISSUE THREAD

**Issue by bitspook** [gajus/pragmatist#2]
Most editors already have plugins for utilising tools like eslint/scss-lint to show the violations inside the editor. They use eslint/scss-lint tools with the configuration (rc files)  in the project and can show the errors inside the editor. I find the this extremely helpful.

I think it would be nice if pragmatist could create config files in the project (perhaps with a warning for user to not edit them). What do you think?

**Comment by gajus** [comment]
It is not an easy task to create ESLint configuration. Pragmatist ([Canonical](https://github.com/gajus/canonical), to be more specific) utilises separate configuration files, namely:
- https://github.com/gajus/eslint-config-canonical
- https://github.com/gajus/eslint-config-canonical-jsdoc
- https://github.com/gajus/eslint-config-canonical-react

That in turn depend on third-party extensions:
- https://github.com/yannickcr/eslint-plugin-react
- https://github.com/babel/eslint-plugin-babel
- https://github.com/gajus/eslint-plugin-jsdoc

How can an editor use these third-party plugins?

**Comment by bitspook** [comment]
I am not sure about others (although I am sure they use similar), but Emacs has a plugin called “flycheck”. This plugin make use of third party checkers like /usr/bin/eslint, run them on the opened file and mark the errors. Pretty simple stuff.

If creating config files is more work, I guess I’ll simply create “flycheck” adaptor for pragmatist. But that would still leave other editors in limbo.

**Comment by bitspook** [comment]
Am closing this issue. I think building my own adaptpor is the way to go.
