### ISSUE TITLE
Allow stdin and stdout

### ISSUE THREAD

**Issue by bitspook** [gajus/pragmatist#3]
Running it on entire tree takes a lot of time. Would be great if we could run it on per file bases, or even better if it could take input from stdin (but that's asking too much perhaps).

**Comment by gajus** [comment]
What is the reason you'd prefer stdin over referring to a specific file?

**Comment by gajus** [comment]
Either is possible with relatively the same amount of effort.

**Comment by gajus** [comment]
For the record, the only thing that takes a lot of time is linting. Specifically, https://github.com/gajus/eslint-plugin-jsdoc ESLint plugin that is ridiculously slow.

This is the reason I have separated `watch` into multiple subcommands (specifically, `watch-test` being the most used and `watch-lint` used only when ensuring that code validates against the linting rules.)

**Comment by bitspook** [comment]
> What is the reason you'd prefer stdin over referring to a specific file?

 Ability to directly pass text makes it easier to write tools like editor plugins which can simply pass the tool the content of the buffer (file) they're visiting (whether temporary or have presence on HD). If it can take text from stdin, linting for unsaved files can be made possible, otherwise we'd have to wait for the file to get saved to hard-disk. Some old-school tools (like Emacs) have better support for directly passing text to tools, and getting the results. I built a [css-comb wrapper](https://github.com/channikhabra/css-comb.el/blob/master/css-comb.el) for emacs some time back, and it was 3X the work just because css-comb won't accept stdin and won't provide results in stdout. 

So stdin and stdout support would be very helpful for developing editor plugins, and integration with other tools as well.

More personally, more often than not I create temporary files which never touch the holy lands of hard-disk. Ability to pass them via stdin would save creating temporary files in this use-case as well.

I also assume that tabular form is the only form in which pragmatist provide a report of errors. I guess I'll have to write a parser for that when I go on to make an editor plugin (will be all on me, my editor my problem). The way these plugins (at least the one I use) work is:
- They pass the file's content to the tools like eslint/pragmatist
- The tool give them a report (on stdout or some other way, stdout is best) with error messages
- The plugin parses that report to check on which file and column the error is for, and what's the error message
- The plugin highlights that line and word, and shows the error message when user hover there (or take their cursor on the highlighted part)

e.g

![screen shot 2015-11-19 at 10 18 17 pm](https://cloud.githubusercontent.com/assets/1437091/11277191/7af59820-8f0b-11e5-8022-498a60198bbd.png)

(Notice the error message at the end)

**Comment by gajus** [comment]
> I also assume that tabular form is the only form in which pragmatist provide a report of errors. I guess I'll have to write a parser for that when I go on to make an editor plugin (will be all on me, my editor my problem). The way these plugins (at least the one I use) work is:

It is very easy to add JSON output.

Thats a separate issue, though.

**Comment by bitspook** [comment]
> Thats a separate issue, though.

Created #6

**Comment by gajus** [comment]
> Ability to directly pass text makes it easier to write tools like editor plugins which can simply pass the tool the content of the buffer (file) they're visiting (whether temporary or have presence on HD). If it can take text from stdin, linting for unsaved files can be made possible, otherwise we'd have to wait for the file to get saved to hard-disk.

I will implement the stdin/stdout.

Regarding the output, do you need anything beyond (?):

``` sh
cat ./test.js | pragmatist --stdin --linter js --output-format json
```

**Comment by bitspook** [comment]
I guess not. As long as we are getting the full cycle (input to output) without needing to deal with files, I shall not need anything else.

**Comment by gajus** [comment]
https://github.com/gajus/canonical/issues/6
