### ISSUE TITLE
Absurd SCSS warnings

### ISSUE THREAD

**Issue by bitspook** [gajus/pragmatist#5]
<img width="1068" alt="screen shot 2015-11-19 at 8 53 29 pm" src="https://cloud.githubusercontent.com/assets/1437091/11274629/afc24500-8eff-11e5-8b7f-e886c8cab468.png">

Also, it does not seem to have rule for separating blocks of styles with empty lines. That was a nice one, made scss files look much cleaner and sensible.

**Comment by gajus** [comment]
Please open this with https://github.com/gajus/canonical (two separate issues). It is canonical that does all the linting.
