### ISSUE TITLE
Faulty builds for browser in pragmatist 2.3.0

### ISSUE THREAD

**Issue by bitspook** [gajus/pragmatist#9]
When building for browser with `pragmatist build --browser`, in the `dist/index.js` files it's adding this line:

``` js
var _register = require('/Users/channi/Documents/Work/applaudience/showtimes-components/react-showtimes-calendar/node_modules/source-map-support/register.js');
```

Which is breaking the published packages.

**Comment by gajus** [comment]
Using mocha `-r` option instead of babel plugin as suggested in https://github.com/knpwrs/gulp-spawn-mocha/issues/25.

**Comment by gajus** [comment]
Version 2.3.1 published to NPM.
